version: '3'

tasks:
  install:
    cmds:
      - npm install
    desc: Install project dependencies

  dev:
    cmds:
      - npm run dev
    desc: Start the development server

  build:
    cmds:
      - npm run build
    desc: Build the project for production

  clean:
    cmds:
      - rm -rf dist
      - rm -rf node_modules
    desc: Clean up generated files and dependencies

  assets:
    cmds:
      - npm run assets
    desc: Process and optimize game assets

  deploy:
    cmds:
      - npm run build
      - npm run deploy
    desc: Build and deploy the game

  analyze:
    cmds:
      - npm run analyze
    desc: Analyze the bundle size

  update:
    cmds:
      - npm update
      - npm audit fix
    desc: Update dependencies and fix vulnerabilities

  default:
    desc: Run default tasks
    deps:
      - install
      - build
